server:
  port: 8082

spring:
  application:
    name: game-service

  datasource:
    url: jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.tdhhdbipbnlfdjlbxege
    password: ${SUPABASE_SERVER_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      connection-init-sql: SET search_path TO public
      maximum-pool-size: ${DB_POOL_MAX_SIZE:5}
      minimum-idle: ${DB_POOL_MIN_IDLE:0}
      initialization-fail-timeout: 60000

  sql:
    init:
      mode: always

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    
    hibernate:
      ddl-auto: validate

    properties:
      '[format_sql]': true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        '[default_schema]': public

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://tdhhdbipbnlfdjlbxege.supabase.co/auth/v1
  
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD:}
      ssl:
        enabled: ${REDIS_SSL:false}
      timeout: 2s

supabase:
  jwt:
    secret: ${SUPABASE_JWT_SECRET}
  url: ${SUPABASE_URL}
  service:
    key: ${SUPABASE_SERVICE_KEY}

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
